// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pascalallen/es-go/internal/es-go/infrastructure/messaging"
	"github.com/pascalallen/es-go/internal/es-go/infrastructure/storage"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func InitializeContainer() Container {
	eventStore := storage.NewEventStoreDb()
	connection := messaging.NewRabbitMQConnection()
	commandBus := messaging.NewRabbitMqCommandBus(connection)
	queryBus := messaging.NewSynchronousQueryBus()
	container := NewContainer(eventStore, connection, commandBus, queryBus)
	return container
}
